[build]
  # Directory to change to before starting a build
  base = "client/"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "build/"

  # Default build command with legacy peer deps
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  # Node.js version (React 19 works better with Node 20+)
  NODE_VERSION = "20"
  # NPM configuration
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
